In [1]:
import numpy as np

In [2]:
def linear_hypothesis(theta, x):
    return theta[0] + theta[1] * x

In [3]:
def cost_function(theta, x_parameters, y_parameters):
    m = len(x_parameters)
    J = (1/(2*m))
    sum_ = sum((linear_hypothesis(theta, x) - y) ** 2
        for x, y in zip(x_parameters, y_parameters))
    
    return J * sum_

In [36]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([1, 2, 3])
theta = np.array([0, 0.0])

cost_function(theta, x, y)

array([1.25, 1.25, 1.25])

In [51]:
def normal_equation(X, y):
    X = np.vstack(
        (np.ones((1, X.shape[-1])), X))
    
    result = np.dot(X.transpose(), X)
    print(result)
#     print(np.dot(X.transpose(), X))

In [52]:
normal_equation(x, y)

[[18. 23. 28.]
 [23. 30. 37.]
 [28. 37. 46.]]


In [12]:
np.ones((1, 2))

array([[1., 1.]])

(2, 3)